name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ clang-tidy

    - name: Build
      run: g++ -std=c++11 -Wall -Wextra -pedantic homework.cpp -o homework

    - name: Run clang-tidy
      run: clang-tidy homework.cpp -- -std=c++11
